# Site settings
baseurl: "github.com/hbhasin/Image-Recognition-with-Deep-Learning"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
